### ISSUE TITLE
Update CMPE350 pages

### ISSUE THREAD

**Issue by doganulus** [bouncmpe/bouncmpe.github.io#25]

**Comment by ThoAppelsin** [comment]
Bu düzenlemeyi nasıl yapacağım?

**Comment by doganulus** [comment]
You can use `content/courses/cmpe344.en.md` and `content/courses/cmpe344.tr.md` as templates for your course. Both English and Turkish are requested.

Steps to go there as usual:
1. Fork the repo and clone locally
2. Make changes and commit
3. Push it to your fork
4. Make a pull request to the original repo

**Comment by doganulus** [comment]
Reopened for an investigation of former instructors and a candidate thumbnail picture (or ideas) that represent the course.
