### ISSUE TITLE
Add mugshots

### ISSUE THREAD

**Issue by doganulus** [bouncmpe/bouncmpe.github.io#82]
We need to add photos of the people in the department. First,

- [ ] Current Faculty
- [ ] Current Assistants
- [ ] Administrative Staff

We will manage it on a single branch and merge it once.

**Comment by Mutti499** [comment]
Updated the mugshots in the [PR](https://github.com/bouncmpe/bouncmpe.github.io/pull/74).
Merged the main to the branch in order to keep it in sync. 
After additions of our friends @beyzanurdeniz @umutseki we are ready to go.

**Comment by beyzanurdeniz** [comment]
Also updated the same branch with 2nd quarter of people.
