### ISSUE TITLE
Course Learning Outcome -> Course Learning Outcomes

### ISSUE THREAD

**Issue by vanderberk** [bouncmpe/bouncmpe.github.io#96]
ABET çoğul kullanıyor. Ders sayfalarında şu değişiklik yapılırsa iyi olur:
Course Learning Outcome -> Course Learning Outcomes

**Comment by doganulus** [comment]
@beyzanurdeniz Bütün ders sayfaları için kontrol edebilir misin? Berk hocanın önerdiği değişikliği yapalım.
